name: test_flutter
description: test flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  riverpod: ^2.3.6
  http: ^0.13.6
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  retrofit: ^4.0.1
  dio: ^5.2.0+1
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  retrofit_generator: ^7.0.1
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0



flutter: 

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/json/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: fonts/SF-Pro-Display-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/SF-Pro-Display-LightItalic.otf
          weight: 400
          style: italic
        - asset: fonts/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic
  uses-material-design: true